### ISSUE TITLE
tema component

### ISSUE THREAD

**Issue by L3v3L** [vostpt/website-vostpt#102]
[Homepage review v1](https://github.com/vostpt/website-vostpt/wiki/Homepage-review-v1)
Point: 6
do we really want this section here, there is already a page dedicated to the team, if so, should we show a slide show (3 at a time) of the team, this could be randomized so to always show different members instead of always the same ones.

**Comment by JorgeMiguelGomes** [comment]
This section makes sense to have. Do the slideshow and the random, please.
