### ISSUE TITLE
Google resources missing from privacy policy 

### ISSUE THREAD

**Issue by palmeida** [vostpt/website-vostpt#111]
The vost.pt web site is using Google Analytics, but this is not disclosed in the [Privacy Policy](https://info.vost.pt/privacy-policy/). Several sources indicate that it should, e.g:

https://www.privacypolicies.com/blog/privacy-policy-google-analytics/
https://www.termsfeed.com/blog/privacy-policy-google-analytics/

Google's own [privacy policy](https://policies.google.com/privacy?hl=en-US) states:

> When you visit sites that use Google Analytics, Google and a Google Analytics customer may link information about your activity from that site with activity from other sites that use our ad services.

> Using our systems, data generated through Google Analytics can be linked by the Google Analytics customer and by Google to third-party cookies that are related to visits to other websites.

Furthermore, there seems to be some [controversy regarding the use of Google fonts loaded from fonts.googleapis.com](https://github.com/google/fonts/issues/1495) (which vost.pt also uses), but I don't know the current status on that.

Of course, my preferred solution to this issue would be to not use external resources that enable surveillance of the site's users.

**Comment by L3v3L** [comment]
you seem to have submitted this to the wrong repo, correct repo is found here:
https://github.com/vostpt/current-website

although in future this might be an issue for this repo too.

**Comment by palmeida** [comment]
Oops, sorry. I opened it there now. I'll close this one, it can be reopened if it becomes valid.
