### ISSUE TITLE
post preview component

### ISSUE THREAD

**Issue by L3v3L** [vostpt/website-vostpt#31]
Here is an example of the old design:
![image](https://user-images.githubusercontent.com/30056/56462741-4d1b0d80-63c0-11e9-92f3-66b78924bff4.png)

Here is an example of where to get inspiration from:
![image](https://user-images.githubusercontent.com/30056/56462749-68861880-63c0-11e9-8555-b5735f178dc3.png)

**Comment by VOSTPortugal** [comment]
Right on! /JMG
